name: Automated Python Script

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      COPERNICUS_USERNAME: ${{ secrets.COPERNICUS_USERNAME }}
      COPERNICUS_PASSWORD: ${{ secrets.COPERNICUS_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests numpy copernicusmarine boto3

    # - name: Execute Python for Phytoplankton Functional Types
    #   run: python PFTs.py

    # - name: Execute Python for Transparency 
    #   run: python transp.py

    # - name: Execute Python for Optics 
    #   run: python optics.py

    # - name: Execute Python for Temperature_cmems
    #   run: python sst.py
         
    - name: Execute Python for PP 
      run: python pp.py

    - name: Execute Python for MUR SST 
      run: python ghrsst.py

    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Automated data update" || echo "No changes to commit"
        git push
